package com.kaisha.payroll.employee.entity;

import com.kaisha.payroll.company.entity.Company;
import jakarta.persistence.*;

@Entity
@Table(
        name = "employees",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_employee_company_id",
                        columnNames = {"company_id", "employee_id"}
                )
        }
)
public class Employee {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /*
     * Employee ID is generated by the system.
     *
     * Examples:
     * E001
     * E002
     * E003
     *
     * ADMIN can change only the prefix:
     * E001 -> T001
     */
    @Column(
            name = "employee_id",
            nullable = false,
            length = 50
    )
    private String employeeId;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(
            name = "company_id",
            nullable = false
    )
    private Company company;

    @Column(
            name = "active",
            nullable = false
    )
    private boolean active = true;

    public Employee() {
    }

    public Employee(
            Long id,
            String employeeId,
            Company company,
            boolean active
    ) {
        this.id = id;
        this.employeeId = employeeId;
        this.company = company;
        this.active = active;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }
}